### PR TITLE
Port from pyexiv2 to GExiv2.

### PR DESCRIPTION
**Pull request by ghost**
This is the necessary first step in porting to Python 3 at a later date.

This commit drops the dependency on python-pyexiv2 package and introduces a new dependency on gir1.2-gexiv2-0.4 package instead.

Thanks.

### CODE REVIEW

**Comment by ghost** [comment]
Gave up waiting.

**Comment by tiagovaz** [comment]
oh sorry, i don't really follow this github thing. I use to keep track of my bugs in debian bts... my fault. Merging now.

**Comment by ghost** [comment]
Hmmm, did you test it? It's a small diff but I'm terrified that it might have bitrotted after a year of just sitting around. I'm not _aware_ of anything that would have changed to break it, but man, you just merged something I haven't looked at in literally a year ;-)

**Comment by tiagovaz** [comment]
Hi,

On Sat, Mar 15, 2014 at 04:08:16AM -0700, Robert Bruce Park wrote:

> Hmmm, did you test it? It's a small diff but I'm terrified that it might have bitrotted after a year of just sitting around. I'm not _aware_ of anything that would have changed to break it, but man, you just merged something I haven't looked at in literally a year ;-)

Yes, It seems ok. I'm testing it before pushing to Debian, thanks for
warning :)

## 

---

  .''`.  Tiago Bortoletto Vaz                         GPG  :      4096R/E4B6813D
 : :' :  http://acaia.ca/~tiago                       XMPP : tiago at jabber.org
`. `'   tiago _at_ {acaia.ca, debian.org}            IRC  :       tiago at OFTC

##    `-    Debian GNU/Linux - The Universal OS               http://www.debian.org

**Pull request merged**
